# Copyright (c) 2018-present eyeo GmbH
#
# This module is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---

# provision-custom-systems.yml
ansible_admin_sshd_config__to_merge:
  All:
    AllowAgentForwarding: "yes"

# tasks/ansible-admin.yml
ansible_admin_packages__to_merge:
  "{{ ansible_admin_default_packages }}"

# tasks/ansible.yml
ansible_packages__to_merge:
  "{{ ansible_default_packages }}"

# tasks/ansible-admin.yml
custom_ansible_user:
  comment: "Ansible Admin"
  generate_ssh_key: true
  group: "ansible"
  home: "/srv/ansible"
  home_mode: "0750"
  name: "ansible"
  ssh_key_bits: 4096
  ssh_key_comment: "ansible@{{ ansible_fqdn }}"

# tasks/ansible-admin.yml
ansible_admin_groups__to_merge:
  "{{ custom_ansible_user.group }}":
    name: "{{ custom_ansible_user.group }}"
    state: "present"

# tasks/ansible-admin.yml
ansible_admin_users__to_merge:
  "{{ custom_ansible_user.name }}":
    "{{ custom_ansible_user }}"

# tasks/ansible-admin.yml
ansible_admin_paths__to_merge:
  "{{ custom_ansible_user.home }}/inventory":
    state: "link"
    dest: "/etc/ansible"
    src: "{{ custom_ansible_user.home }}/inventory"

# tasks/ansible-admin.yml
ansible_admin_commands__to_merge:
  git_checkout_inventory:
    cmd: "git init '{{ custom_ansible_user.home }}/inventory'"
    creates: "{{ custom_ansible_user.home }}/inventory/.git"
    become_user: "{{ custom_ansible_user.name }}"

# When users are able to access confidential files in the Ansible inventory
# their home directory shall not be accessible to other users, in order to
# protect sensitive information. Hence the default home directory access mode
# of custom_users on Ansible admin hosts is based on whether a user is a
# member of the "ansible" group. Refer to the provision-ansible-admin-hosts.yml
# playbook and the tasks/users.yml file for more information.
custom_users_default_home_mode:
  "{{ (custom_user_name in custom_ansible_group_members | default([]))
    | ternary('0750', '0755') }}"

# Log ansible-playbook runs
ansible_admin_log_paths__to_merge:
  /var/log/ansible:
    owner: "root"
    group: "ansible"
    mode: "0755"
    state: "directory"
  /var/log/ansible/log:
    owner: "root"
    group: "ansible"
    mode: "0664"
    state: "touch"
  /etc/logrotate.d/ansible:
    content: |
      /var/log/ansible/log {
          compress
          create 664 root ansible
          daily
          dateext
          dateformat .%Y-%m-%d
          dateyesterday
          delaycompress
          missingok
          notifempty
          rotate {{ ansible_admin_log_count | default('14') }}
      }
    state: "copy"
