# Copyright (c) 2020-present eyeo GmbH
#
# This module is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---

apk_signing_hosts_custom_packages__to_merge:
  default-jdk: "present"

apk_signing_hosts_groups__to_merge:
  "{{ apk_signing_group_name }}":
    name: "{{ apk_signing_group_name }}"

apk_signing_hosts_paths__to_merge:
  "{{ apk_signing_directory }}":
    path: "{{ apk_signing_directory }}"
    state: "directory"
    owner: "root"
    group: "{{ apk_signing_group_name | mandatory }}"
    mode: "0750"
  "{{ apk_signing_group_credentials_source }}":
    dest: "{{ apk_signing_group_credentials_source }}"
    mode: "0640"
    state: "copy"
    content: |
      APK_KEYSTORE_NAME={{ APK_KEYSTORE_NAME | mandatory }}
      APK_KEY_ALIAS_NAME={{ APK_KEY_ALIAS_NAME | mandatory }}
      APK_STOREPASS={{ APK_STOREPASS | mandatory }}
      APK_KEYPASS={{ APK_KEYPASS | mandatory }}
    validate:
      "/bin/sh -n %s"
    owner: "root"
    group: "{{ apk_signing_group_name }}"
  /usr/local/bin/apk_signer:
    state: "template"
    src: "./files/apk_signer.j2"
    dest: "/usr/local/bin/apk_signer"
    mode: "0755"
    validate: "/bin/sh -n %s"
