# Copyright (c) 2022-present eyeo GmbH
#
# This module is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---

crumbs_filter_server_custom_apache_config: |
  RewriteEngine On

  {{ filter_server_prerequisite_custom_apache_config
   | default(default_filter_server_prerequisite_custom_apache_config) }}

  # Deny access to base structure and only explicitly allow
  # what's available later, e.g crumbs-lists
  <Directory /var/www/easylist>
    Require all denied
    Options -Indexes
  </Directory>

  {{ filter_server_skip_mod_brotli_config
   | default(default_filter_server_skip_mod_brotli_config) }}

  {{ filter_server_skip_mod_deflate_config
   | default(default_filter_server_skip_mod_deflate_config) }}

  {{ crumbs_filter_server_header_custom_apache_config
   | default(default_crumbs_filter_server_header_custom_apache_config) }}

  {{ crumbs_filter_server_test_custom_apache_config
   | default(default_crumbs_filter_server_test_custom_apache_config) }}

  {{ crumbs_filter_server_base_custom_apache_config
   | default(default_crumbs_filter_server_base_custom_apache_config) }}

  {{ crumbs_filter_server_privacy_custom_apache_config
   | default(default_crumbs_filter_server_privacy_custom_apache_config) }}

default_crumbs_filter_server_base_custom_apache_config: |
  <LocationMatch ^/crumbs(.*)(\.txt|\.json)(\.gz|\.br)?>
    Require all granted
  </LocationMatch>

default_crumbs_filter_server_test_custom_apache_config: |
  <LocationMatch ^/easytest.txt>
    Require all granted
  </LocationMatch>

# yamllint disable rule:line-length
default_crumbs_filter_server_privacy_custom_apache_config: |
  # Applied when CRUMBS privacy friendly lists are requested from Germany.
  RewriteCond %{ENV:GEOIP_COUNTRY_CODE} ^DE$ [OR]
  RewriteCond %{ENV:GEOIP_COUNTRY_CODE_V6} ^DE$
  RewriteRule ^/crumbs-privacy-friendly.txt /crumbs-privacy-friendly-germany.txt [R=302,L]

  # Applied when CRUMBS privacy friendly diffs are requested from Germany.
  RewriteCond %{ENV:GEOIP_COUNTRY_CODE} ^DE$ [OR]
  RewriteCond %{ENV:GEOIP_COUNTRY_CODE_V6} ^DE$
  RewriteRule ^/v3/diff/crumbs\-privacy\-friendly/(.+) /v3/diff/crumbs-privacy-friendly-germany/$1 [L]
# yamllint enable rule:line-length

default_crumbs_filter_server_header_custom_apache_config: |
  <FilesMatch "(crumbs_abb\.json|crumbs_extension\.json)">
    # Append Crumbs CC header
    Header append X-Crumbs-Country-Code "expr=%{ENV:GEOIP_COUNTRY_CODE}"
  </FilesMatch>
