# Copyright (c) 2022-2023 eyeo GmbH
#
# This module is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---

# yamllint disable rule:line-length
crumbs_filter_server_custom_apache_config: |
  RewriteEngine On

  {{ filter_server_prerequisite_custom_apache_config
   | default(default_filter_server_prerequisite_custom_apache_config) }}

  {{ filter_server_skip_mod_brotli_config
   | default(default_filter_server_skip_mod_brotli_config) }}

  {{ filter_server_skip_mod_deflate_config
   | default(default_filter_server_skip_mod_deflate_config) }}

  {{ crumbs_filter_server_header_custom_apache_config
   | default(default_crumbs_filter_server_header_custom_apache_config) }}

  # Previously here listed rewrite rules have been moved to {{ filter_server_document_root_path }}/.htaccess
  # due to the responsibility shift to FLOPS

# yamllint enable rule:line-length

default_crumbs_filter_server_header_custom_apache_config: |
  <FilesMatch "(crumbs_abb\.json|crumbs_extension\.json)">
    # Append Crumbs CC header
    <If "%{IPV6} == 'on'">
    Header append X-Crumbs-Country-Code "expr=%{ENV:GEOIP_COUNTRY_CODE_V6}"
    </If>
    <Else>
    Header append X-Crumbs-Country-Code "expr=%{ENV:GEOIP_COUNTRY_CODE}"
    </Else>
    Header append X-Crumbs-Language-Code "expr=%{HTTP:Accept-Language}"
  </FilesMatch>
