# Copyright (c) 2018-present eyeo GmbH
#
# This module is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---

# https://httpd.apache.org/docs/current/mod/
eyeo_cms_apache2_modules__to_merge:
  geoip: &apache2_nonstandard_module
    package: true
  headers: &apache2_standard_module
    package: false
  expires:
    *apache2_standard_module
  proxy:
    *apache2_standard_module
  proxy_fcgi:
    *apache2_standard_module
  proxy_http:
    *apache2_standard_module
  rewrite:
    *apache2_standard_module
  socache:
    <<: *apache2_standard_module
    name: "socache_shmcb"
  ssl:
    *apache2_standard_module

# https://httpd.apache.org/docs/2.4/mod/core.html#virtualhost
# _SITE_NAME_ comes from a replace() filter on input
# yamllint disable rule:line-length
eyeo_cms_shared_apache_config: |
  ServerName _SITE_NAME_
  ServerAlias *._SITE_NAME_

  ErrorLog ${APACHE_LOG_DIR}/_SITE_NAME_-error.log
  CustomLog ${APACHE_LOG_DIR}/_SITE_NAME_-access.log combined

  # if necessary for rewrite debug
  #LogLevel alert rewrite:trace3

#  DocumentRoot "/var/www/_SITE_NAME_"
  <Directory "/var/www/_SITE_NAME_">
    AllowOverride All
    Require all granted
  </Directory>

  RewriteEngine On

  # https://issues.adblockplus.org/ticket/4068
  RewriteCond %{HTTP_HOST} ^(.+)\.$"
  RewriteRule ^(.*)$ http://%1/$1 [R=permanent,L]

  # VirtualDocumentRoot implementation within mod_rewrite
  RewriteMap  lowercase  int:tolower
  RewriteRule ^ - [E=virtual_document_root:/var/www/${lowercase:%{HTTP_HOST}}]

  AddDefaultCharset UTF-8
  DefaultType text/html
  DirectoryIndex index
  RewriteRule ^ - [E=index_page:index]

  ExpiresDefault "access plus 1 day"

  # Match Accept-Language header against available languages
  # TODO: replace with Apache mod_negotiation which actually implements this properly
  RewriteRule ^ - [E=preferredLang:en]

  RewriteCond %{HTTP:Accept-Language} ^(\w\w)\b
  RewriteRule ^ - [E=preferredLang:%1]

  RewriteCond %{HTTP:Accept-Language} ^\w\w-(\w\w)\b
  RewriteRule ^ - [E=preferredRegion:%1]

  RewriteCond %{QUERY_STRING} fb_locale=(\w\w)_(\w\w)
  RewriteRule ^ - [E=preferredLang:%1,E=preferredRegion:%1]

  # Redirect canonical URLs to language-specific versions
  RewriteCond %{ENV:virtual_document_root}/%{ENV:preferredLang}_%{ENV:preferredRegion}%{REQUEST_URI} -f
  RewriteRule ^ %{ENV:virtual_document_root}/%{ENV:preferredLang}_%{ENV:preferredRegion}%{REQUEST_URI} [L]

  RewriteCond %{ENV:virtual_document_root}/%{ENV:preferredLang}%{REQUEST_URI} -f
  RewriteRule ^ %{ENV:virtual_document_root}/%{ENV:preferredLang}%{REQUEST_URI} [L]

  RewriteCond %{ENV:virtual_document_root}/en%{REQUEST_URI} -f
  RewriteRule ^ %{ENV:virtual_document_root}/en%{REQUEST_URI} [L]

  # Redirect language URIs if no translations are found for the requested page
  RewriteCond %{REQUEST_URI} ^/([a-z][a-z]\_[A-Z][A-Z])(/.+)
  RewriteCond %{ENV:virtual_document_root}/%{REQUEST_URI} !-f
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME}/%{ENV:index_page} !-f
  RewriteRule ^/([a-z][a-z])\_([A-Z][A-Z])(/.+) %{ENV:virtual_document_root}/$1$3 [R]

  # if there is no language translation, try canonical page for default language
  # example /es/page -> /page
  RewriteCond %{REQUEST_URI} !^/js/.+
  RewriteCond %{REQUEST_URI} ^/([a-z][a-z])/(.+)
  RewriteCond %{ENV:virtual_document_root}/%{REQUEST_URI} !-f
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME}/%{ENV:index_page} !-f
  RewriteRule ^/([a-z][a-z])(/.+) %{ENV:virtual_document_root}/$2 [R]
# yamllint enable rule:line-length

  # catch-all, DocumentRoot implementation within mod_rewrite
  RewriteRule "^/(.*)$" %{ENV:virtual_document_root}/$1 [L]
