# Copyright (c) 2019-present eyeo GmbH
#
# This module is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---

# tasks/paths.yml
eyeo_apache2_custom_paths__to_merge:
  "/var/log/eyeo-apache2":
    state: "directory"
    mode: "0755"
    group: "adm"
  "/etc/eyeo-apache2-logrotate.conf":
    name: "{{ (ansible_distribution == 'Debian' and
               ansible_distribution_version|int < 10)
            | ternary('/etc/eyeo-apache2-logrotate.conf',
                      '/etc/logrotate.d/local-eyeo-apache2')
            }}"
    state: "copy"
    # basically /etc/logrotate.d/apache2 from Debian 10 with exceptions
    # and with basic invoke-rc.d logging
    # yamllint disable rule:line-length
    content: |
      /var/log/eyeo-apache2/*.log {
        daily
        missingok
        rotate {{ apache2_logrotate_count | default('14') }}
        dateext
        dateyesterday
        dateformat .%Y-%m-%d
        compress
        delaycompress
        notifempty
        create 640 root adm
        sharedscripts
        postrotate
                if invoke-rc.d apache2 status > /var/log/eyeo-apache2/apache2-status.log 2>&1; then \
                    invoke-rc.d apache2 reload > /var/log/eyeo-apache2/apache2-reload.log 2>&1; \
                fi;
        endscript
        prerotate
                if [ -d /etc/logrotate.d/httpd-prerotate ]; then \
                        run-parts /etc/logrotate.d/httpd-prerotate; \
                fi; \
        endscript
      }
    # yamllint enable rule:line-length
    mode: "0644"
  "/etc/cron.d/local-logrotate-eyeo-apache2":
    state: "{{ (ansible_distribution == 'Debian' and
                ansible_distribution_version|int < 10)
             | ternary('copy', 'absent')
             }}"
    content: |
      PATH=/sbin:/bin:/usr/sbin:/usr/bin
      0 0 * * * root /usr/sbin/logrotate /etc/eyeo-apache2-logrotate.conf
    mode: "0644"

# roles/apache2/defaults/main.yml
eyeo_apache2_conf__to_merge:
  local-eyeo-combined-logformat:
    # yamllint disable rule:line-length
    configuration: |
      LogFormat "%h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\" \"%{X-Forwarded-For}i\" %{REQUEST_SCHEME}x \"%{Accept-Language}i\" \"%{Host}i\" \"%{X-Client-ID}i\"" eyeo-combined
    # yamllint enable rule:line-length
    enabled: true

# prerequisite for LogFormat %{...}x
# roles/apache2/defaults/main.yml
eyeo_apache2_modules__to_merge:
  ssl: &apache2_standard_module
    package: false
