# Copyright (c) 2018-present eyeo GmbH
#
# This module is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---

# https://httpd.apache.org/docs/current/mod/
eyeo_cms_apache2_modules__to_merge:
  geoip: &apache2_nonstandard_module
    package: true
  headers: &apache2_standard_module
    package: false
  expires:
    *apache2_standard_module
  proxy:
    *apache2_standard_module
  proxy_fcgi:
    *apache2_standard_module
  proxy_http:
    *apache2_standard_module
  rewrite:
    *apache2_standard_module
  socache:
    <<: *apache2_standard_module
    name: "socache_shmcb"
  ssl:
    *apache2_standard_module

# tasks/paths.yml
eyeo_cms_custom_paths__to_merge:
  "/var/log/eyeo-apache2":
    state: "directory"
    mode: "0755"
    group: "adm"
  "/etc/eyeo-apache2-logrotate.conf":
    state: "copy"
    # basically /etc/logrotate.d/apache2 from Debian 10 with exceptions
    content: |
      /var/log/eyeo-apache2/*.log {
        daily
        missingok
        rotate {{ apache2_logrotate_count | default('14') }}
        dateext
        dateyesterday
        dateformat .%Y-%m-%d
        compress
        delaycompress
        notifempty
        create 640 root adm
        sharedscripts
        postrotate
                if invoke-rc.d apache2 status > /dev/null 2>&1; then \
                    invoke-rc.d apache2 reload > /dev/null 2>&1; \
                fi;
        endscript
        prerotate
                if [ -d /etc/logrotate.d/httpd-prerotate ]; then \
                        run-parts /etc/logrotate.d/httpd-prerotate; \
                fi; \
        endscript
      }
    mode: "0644"
  "/etc/cron.d/local-logrotate-eyeo-apache2":
    state: "copy"
    content: |
      0 0 * * * root /usr/sbin/logrotate /etc/eyeo-apache2-logrotate.conf
    mode: "0644"
  "/etc/apache2/conf-available/local-eyeo-combined-logformat.conf":
    state: "copy"
    # yamllint disable rule:line-length
    content: |
      LogFormat "%h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\" \"%{X-Forwarded-For}i\" %{REQUEST_SCHEME}x \"%{Accept-Language}i\" \"%{Host}i\" \"%{X-Client-ID}i\"" eyeo-combined
    # yamllint disable rule:line-length
    mode: "0644"
  "/etc/apache2/conf-enabled/local-eyeo-combined-logformat.conf":
    state: "link"
    src: "../conf-available/local-eyeo-combined-logformat.conf"
    force: true

# https://httpd.apache.org/docs/2.4/mod/core.html#virtualhost
# _SITE_NAME_ comes from a replace() filter on input
eyeo_cms_shared_apache_config: |
  {{ eyeo_cms_shared_apache_config_preamble }}

  {{ eyeo_cms_shared_apache_config_specifics }}

# yamllint disable rule:line-length
eyeo_cms_shared_apache_config_preamble: |
  ServerName _SITE_NAME_

  ErrorLog /var/log/eyeo-apache2/_SITE_NAME_-error.log
  CustomLog /var/log/eyeo-apache2/_SITE_NAME_-access.log eyeo-combined

  # if necessary for rewrite debug
  #LogLevel alert rewrite:trace3

  DocumentRoot "/var/www/_SITE_NAME_"
  <Directory "/var/www/_SITE_NAME_">
    AllowOverride All
    Require all granted
  </Directory>

  RewriteEngine On

  # https://issues.adblockplus.org/ticket/4068
  RewriteCond %{HTTP_HOST} ^(.+)\.$"
  RewriteRule ^(.*)$ http://%1/$1 [R=permanent,L]
# yamllint enable rule:line-length

# yamllint disable rule:line-length
eyeo_cms_shared_apache_config_specifics: |
  AddDefaultCharset UTF-8
  DefaultType text/html
  DirectoryIndex index
  RewriteRule ^ - [E=index_page:index]

  ExpiresDefault "access plus 1 day"

  # Match Accept-Language header against available languages
  # TODO: replace with Apache mod_negotiation which actually implements this properly
  RewriteRule ^ - [E=preferredLang:en]

  RewriteCond %{HTTP:Accept-Language} ^(\w\w)\b
  RewriteRule ^ - [E=preferredLang:%1]

  RewriteCond %{HTTP:Accept-Language} ^\w\w-(\w\w)\b
  RewriteRule ^ - [E=preferredRegion:%1]

  RewriteCond %{QUERY_STRING} fb_locale=(\w\w)_(\w\w)
  RewriteRule ^ - [E=preferredLang:%1,E=preferredRegion:%1]

  # Redirect canonical URLs to language-specific versions
  RewriteCond %{DOCUMENT_ROOT}/%{ENV:preferredLang}_%{ENV:preferredRegion}%{REQUEST_URI} -f
  RewriteRule ^ /%{ENV:preferredLang}_%{ENV:preferredRegion}%{REQUEST_URI} [L]

  RewriteCond %{DOCUMENT_ROOT}/%{ENV:preferredLang}%{REQUEST_URI} -f
  RewriteRule ^ /%{ENV:preferredLang}%{REQUEST_URI} [L]

  RewriteCond %{DOCUMENT_ROOT}/en%{REQUEST_URI} -f
  RewriteRule ^ /en%{REQUEST_URI} [L]

  # Redirect language URIs if no translations are found for the requested page
  RewriteCond %{REQUEST_URI} ^/([a-z][a-z]\_[A-Z][A-Z])(/.+)
  RewriteCond %{DOCUMENT_ROOT}/%{REQUEST_URI} !-f
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME}/%{ENV:index_page} !-f
  RewriteRule ^/([a-z][a-z])\_([A-Z][A-Z])(/.+) /$1$3 [R]

  # if there is no language translation, try canonical page for default language
  # example /es/page -> /page
  RewriteCond %{REQUEST_URI} !^/js/.+
  RewriteCond %{REQUEST_URI} ^/([a-z][a-z])(/.+)
  RewriteCond %{DOCUMENT_ROOT}/%{REQUEST_URI} !-f
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME}/%{ENV:index_page} !-f
  RewriteRule ^/([a-z][a-z])(/.+) $2 [R]
# yamllint enable rule:line-length
