# Copyright (c) 2021-present eyeo GmbH
#
# This module is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---

filter_server_custom_packages__to_merge:
  wget: "present"

filter_server_custom_users__to_merge:
  rsync:
    name: "{{ filter_server_mirror_user }}"
    comment: "Filter lists mirror user"

filter_server_document_root_path:
  "/var/www/easylist"

filter_server_custom_paths__to_merge:
  /var/www:
    state: "directory"
    mode: "0755"
  /var/www/easylist:
    dest: "{{ filter_server_document_root_path }}"
    state: "directory"
    mode: "0755"
    owner: "{{ filter_server_mirror_user }}"

filter_server_custom_cron_jobs__to_merge:
  mirror:
    name: "mirror_filter_lists"
    minute: "{{ filter_server_mirror_cron_job_minute }}"
    user: "{{ filter_server_mirror_user }}"
    # yamllint disable rule:line-length
    job: >-
      rsync -e "ssh -o CheckHostIP=no" -ltprz --delete --max-delete={{ filter_origin_max_delete }} {{ filter_origin_server_spec }}:. {{ filter_server_document_root_path }}/
    # yamllint enable rule:line-length

# roles/apache2/tasks/main.yml
# provision-apache2-servers.yml
filter_server_apache2_modules__to_merge:
  rewrite: &apache2_standard_module
    package: false
  headers:
    *apache2_standard_module
  brotli:
    *apache2_standard_module
  geoip: &apache2_nonstandard_module
    package: true

# yamllint disable rule:line-length
# This replicates legacy/infrastructure's modules/filterserver/files/site.conf
filter_server_custom_apache_config: |
  RewriteEngine on

  {{ filter_server_keepalive_custom_apache_config
   | default(default_filter_server_keepalive_custom_apache_config) }}

  {{ filter_server_prerequisite_custom_apache_config
   | default(default_filter_server_prerequisite_custom_apache_config) }}

  {{ filter_server_skip_mod_brotli_config
   | default(default_filter_server_skip_mod_brotli_config) }}

  {{ filter_server_skip_mod_deflate_config
   | default(default_filter_server_skip_mod_deflate_config) }}

  {{ filter_server_elem_hide_custom_apache_config
   | default(default_filter_server_elem_hide_custom_apache_config) }}

  {{ filter_server_mobile_anticv_custom_apache_config
   | default(default_filter_server_mobile_anticv_custom_apache_config) }}

  {{ filter_server_minimize_custom_apache_config
   | default(default_filter_server_minimize_custom_apache_config) }}

  {{ filter_server_compliance_custom_apache_config
   | default(default_filter_server_compliance_custom_apache_config) }}

  {{ filter_server_v3_diff_compliance_custom_apache_config
   | default(default_filter_server_v3_diff_compliance_custom_apache_config) }}

  {{ filter_server_safari15_custom_apache_config
   | default(default_filter_server_safari15_custom_apache_config) }}

  {{ filter_server_obsolete_custom_apache_config
   | default(default_filter_server_obsolete_custom_apache_config) }}

  {{ filter_server_a_b_testing_custom_apache_config
   | default(default_filter_server_a_b_testing_custom_apache_config) }}

default_filter_server_keepalive_custom_apache_config: |
  KeepAlive On
  KeepAliveTimeout 0

default_filter_server_prerequisite_custom_apache_config: |
  DocumentRoot {{ filter_server_document_root_path }}
  AddDefaultCharset UTF-8

  RewriteCond %{HTTP_HOST} "^(.+)\.$" [NC]
  RewriteRule "^(.*)" %{REQUEST_SCHEME}://%1$1 [R,L]

  GeoIPEnable On
  GeoIPDBFile {{ custom_geoip_data_path }}/{{ custom_geoip_data_country_ipv4 }} CheckCache
  GeoIPDBFile {{ custom_geoip_data_path }}/{{ custom_geoip_data_country_ipv6 }} CheckCache

default_filter_server_elem_hide_custom_apache_config: |
  #  http://httpd.apache.org/docs/current/env.html
  RewriteCond %{ENV:GEOIP_COUNTRY_CODE} ^DE$ [OR]
  RewriteCond %{ENV:GEOIP_COUNTRY_CODE_V6} ^DE$
  RewriteCond %{QUERY_STRING} (?:^|&)addonName=(?:maxthon|adblockplusie) [OR,NC]
  RewriteCond %{QUERY_STRING} (?:^|&)application=(?:yowser|adblockbrowser) [NC]
  # Store environment variable.
  RewriteRule ^ - [E=NO_ELEM_HIDE:true]

  RewriteCond %{ENV:NO_ELEM_HIDE} =true
  RewriteRule "^/easylist(germany)?\.(.+)" /easylist$1_noelemhide.$2 [R=302,L]
  # couldn't make it simpler
  #RewriteRule ^ - [E=REDIRECT:ELEM_HIDE]
  RewriteCond %{ENV:NO_ELEM_HIDE} =true
  RewriteRule "^/easylistgermany\+easylist\.(.+)" /easylistgermany_noelemhide+easylist_noelemhide.$1 [R=302,L]

# This replicates legacy/infrastructure's modules/filterserver/files/site.conf
# gzip_static setting and is based on the example from:
# https://httpd.apache.org/docs/2.4/mod/mod_deflate.html#precompressed
default_filter_server_skip_mod_deflate_config: |
  # Serve gzip compressed files if they exist and the client accepts gzip.
  RewriteCond "%{HTTP:Accept-encoding}" "gzip"
  RewriteCond "%{DOCUMENT_ROOT}%{REQUEST_FILENAME}\.gz" -s
  RewriteRule "^(.*)\.(json|tpl|txt)$" "$1\.$2\.gz" [QSA]

  # Serve correct content types, and prevent mod_deflate double gzip.
  RewriteRule "\.json\.gz$" "-" [T=application/json,E=no-brotli:1,E=no-gzip:1]
  RewriteRule "\.tpl\.gz$" "-" [T=text/plain,E=no-brotli:1,E=no-gzip:1]
  RewriteRule "\.txt\.gz$" "-" [T=text/plain,E=no-brotli:1,E=no-gzip:1]

  <FilesMatch "(\.json\.gz|\.tpl\.gz|\.txt\.gz)$">
    # Serve correct encoding type.
    Header append Content-Encoding gzip
    # Force proxies to cache gzipped &
    # non-gzipped css/js files separately.
    Header append Vary Accept-Encoding
  </FilesMatch>

default_filter_server_skip_mod_brotli_config: |
  # https://httpd.apache.org/docs/trunk/mod/mod_brotli.html#precompressed
  # Serve brotli compressed files if they exist and the client accepts brotli.
  RewriteCond "%{HTTP:Accept-encoding}" "br"
  RewriteCond "%{DOCUMENT_ROOT}%{REQUEST_FILENAME}\.br" -s
  RewriteRule "^(.*)\.(json|tpl|txt)$" "$1\.$2\.br" [QSA]

  # Serve correct content types, and prevent double compression.
  RewriteRule "\.json\.br$" "-" [T=application/json,E=no-brotli:1,E=no-gzip:1]
  RewriteRule "\.tpl\.br$" "-" [T=text/plain,E=no-brotli:1,E=no-gzip:1]
  RewriteRule "\.txt\.br$" "-" [T=text/plain,E=no-brotli:1,E=no-gzip:1]

  <FilesMatch "(\.json\.br|\.tpl\.br|\.txt\.br)$">
    # Serve correct encoding type.
    Header append Content-Encoding br
    # Force proxies to cache brotli &
    # nonbrotli files separately.
    Header append Vary Accept-Encoding
    # Remove br language, set by mods-enabled/mime.conf
    RemoveLanguage .br
  </FilesMatch>

default_filter_server_mobile_anticv_custom_apache_config: |
  RewriteCond %{QUERY_STRING} (?:^|&)application=org\.adblockplus\.browser(?:\.beta)?
  RewriteRule ^ - [E=MOBILE_ANTICV_LIST:true]

  RewriteCond %{ENV:MOBILE_ANTICV_LIST} =true
  RewriteRule ^/(easylist)\.(.+) /$1+mobile-anti-cv.$2 [L]

  RewriteCond %{ENV:MOBILE_ANTICV_LIST} =true
  RewriteRule ^/(easylist(?:china|czechslovak|dutch|germany|italy|lithuania|polish|portuguese|spanish)\+easylist)\.(.+) /$1+mobile-anti-cv.$2 [L]

  RewriteCond %{ENV:MOBILE_ANTICV_LIST} =true
  RewriteRule ^/((?:abpindo|abpvn|liste_ar\+liste_fr|liste_fr)\+easylist)\.(.+) /$1+mobile-anti-cv.$2 [L]

  RewriteCond %{ENV:MOBILE_ANTICV_LIST} =true
  RewriteRule ^/((?:bulgarian_|indian|israel|korean|latvian|ro|ruad)list\+easylist)\.(.+) /$1+mobile-anti-cv.$2 [L]

# TODO: remove the probably obsolete application=safari setting after verifying
default_filter_server_minimize_custom_apache_config: |
  RewriteCond %{QUERY_STRING} (?:^|&)application=safari [OR]
  RewriteCond %{QUERY_STRING} (?:^|&)addonName=(?:abp\.for\.uc|adblockplussafari|libadblockplus(?:-android)?|aaonly)
  RewriteRule ^ - [E=MIN_LIST:true]

  RewriteCond %{ENV:MIN_LIST} =true
  RewriteRule ^/exceptionrules\.(.+) /exceptionrules-minimal.$1 [L]

  RewriteCond %{ENV:MIN_LIST} =true
  RewriteRule ^/(easylist|easyprivacy|fanboy-social)\.(.+) /$1-minified.$2 [L]

  RewriteCond %{ENV:MIN_LIST} =true
  RewriteRule ^/(easylist(?:china|czechslovak|dutch|germany|italy|lithuania|polish|portuguese|spanish)\+easylist)\.(.+) /$1-minified.$2 [L]

  RewriteCond %{ENV:MIN_LIST} =true
  RewriteRule ^/((?:abpindo|abpvn|bulgarian_list|dandelion_sprouts_nordic_filters|israellist|koreanlist|latvianlist|liste_fr|liste_ar|rolist|ruadlist)\+easylist)\.(.+) /$1-minified.$2 [L]

  RewriteCond %{ENV:MIN_LIST} =true
  RewriteRule ^/indianlist\+easylist\.(.+) /indianlist-full+easylist-minified.$1 [L]

default_filter_server_compliance_custom_apache_config: |
  RewriteCond %{ENV:GEOIP_COUNTRY_CODE} ^CN$ [OR]
  RewriteCond %{ENV:GEOIP_COUNTRY_CODE_V6} ^CN$
  RewriteCond %{QUERY_STRING} (?:^|&)addonName=(?:adblockplus(chrome|firefox|edge|opera))
  RewriteRule ^ - [E=COMPLIANCE_LIST:true]

  RewriteCond %{ENV:GEOIP_COUNTRY_CODE} ^CN$ [OR]
  RewriteCond %{ENV:GEOIP_COUNTRY_CODE_V6} ^CN$
  RewriteCond %{QUERY_STRING} (?:^|&)addonName=(?:adblockplussbrowser)
  RewriteCond %{QUERY_STRING} (?:^|&)application=(?:sbrowser)
  RewriteRule ^ - [E=COMPLIANCE_LIST:true]

  RewriteCond %{ENV:COMPLIANCE_LIST} =true
  RewriteRule ^/easylistchina\+easylist\.(.+) /easylistchina+easylistchina_compliance+easylist.$1 [L]

  RewriteCond %{ENV:GEOIP_COUNTRY_CODE} ^DE$ [OR]
  RewriteCond %{ENV:GEOIP_COUNTRY_CODE_V6} ^DE$
  RewriteRule ^/abp\-filters\-anti\-cv\.(.+) /abp-filters-ger.$1 [L]

  RewriteCond %{ENV:GEOIP_COUNTRY_CODE} ^PL$ [OR]
  RewriteCond %{ENV:GEOIP_COUNTRY_CODE_V6} ^PL$ [OR]
  RewriteCond %{ENV:GEOIP_COUNTRY_CODE} ^ZA$ [OR]
  RewriteCond %{ENV:GEOIP_COUNTRY_CODE_V6} ^ZA$ [OR]
  RewriteCond %{ENV:GEOIP_COUNTRY_CODE} ^IN$ [OR]
  RewriteCond %{ENV:GEOIP_COUNTRY_CODE_V6} ^IN$
  RewriteCond %{QUERY_STRING} (?:^|&)addonName=(?:adblockplus(?:chrome|firefox|opera|edge)?)(?:&|$)
  RewriteCond %{QUERY_STRING} (?:^|&)addonVersion=(?:3\.(?:11\.[4-9]|1[2-9])|[4-9])
  RewriteRule ^/abp\-filters\-anti\-cv\.(.+) /abp-filters-graph.$1 [L]

default_filter_server_safari15_custom_apache_config: |
  RewriteCond %{QUERY_STRING} (?:^|&)application=ios(?:&|$)
  RewriteCond %{QUERY_STRING} (?:^|&)applicationVersion=1[5-9]\.
  RewriteRule ^ - [E=SAFARI15:true]

  RewriteCond %{QUERY_STRING} (?:^|&)application=macos(?:&|$)
  RewriteCond %{QUERY_STRING} (?:^|&)applicationVersion=1(?:0\.1[5-9]|[1-9])
  RewriteRule ^ - [E=SAFARI15:true]

  RewriteCond %{ENV:SAFARI15} =true
  RewriteRule ^/(easylist.*)\.(json(?:\.\w+)?)$ /$1+safari15.$2 [L]

default_filter_server_obsolete_custom_apache_config: |
  RewriteRule ^/advblock\.((?:tpl|txt)(?:\.\w+)?) /ruadlist.$1 [R=302,L]

  RewriteRule ^/Liste_AR\.((?:tpl|txt)(?:\.\w+)?) /liste_ar.$1 [R=302,L]

default_filter_server_v3_diff_compliance_custom_apache_config: |
  # Manifest v3 filter list diffs
  # Rewrite rules to handle v3 filter list diffs.

  # Applied when easylistchina or easylistchina+easylist diffs are requested from China.
  RewriteCond %{ENV:GEOIP_COUNTRY_CODE} ^CN$ [OR]
  RewriteCond %{ENV:GEOIP_COUNTRY_CODE_V6} ^CN$
  RewriteRule ^/v3/diff/easylistchina(\+easylist)?/(.+) /v3/diff/easylistchina+easylistchina_compliance$1/$2 [L]

  # Applied when ABP filters diffs are requested from Germany.
  RewriteCond %{ENV:GEOIP_COUNTRY_CODE} ^DE$ [OR]
  RewriteCond %{ENV:GEOIP_COUNTRY_CODE_V6} ^DE$
  RewriteRule ^/v3/diff/abp\-filters\-anti\-cv/(.+) /v3/diff/abp-filters-ger/$1 [L]

  # Applied when ABP filters diffs are requested from Poland, South Africa or India.
  RewriteCond %{ENV:GEOIP_COUNTRY_CODE} ^PL$ [OR]
  RewriteCond %{ENV:GEOIP_COUNTRY_CODE_V6} ^PL$ [OR]
  RewriteCond %{ENV:GEOIP_COUNTRY_CODE} ^ZA$ [OR]
  RewriteCond %{ENV:GEOIP_COUNTRY_CODE_V6} ^ZA$ [OR]
  RewriteCond %{ENV:GEOIP_COUNTRY_CODE} ^IN$ [OR]
  RewriteCond %{ENV:GEOIP_COUNTRY_CODE_V6} ^IN$
  RewriteRule ^/v3/diff/abp\-filters\-anti\-cv/(.+) /v3/diff/abp-filters-graph/$1 [L]

default_filter_server_a_b_testing_custom_apache_config: |
  # Rewrite rules for A/B testing, see https://jira.eyeo.com/browse/KRK-18
  RewriteCond %{QUERY_STRING} (?:^|&)experiment_id=KRK-18 [NC]
  RewriteCond %{QUERY_STRING} (?:^|&)variant_id=mini [NC]
  RewriteRule ^/exceptionrules\.((?:txt)(?:\.gz)?) /aa-variants/aa_google.$1 [L]

# yamllint enable rule:line-length
