# Copyright (c) 2020-present eyeo GmbH
#
# This module is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---

gluster_version_major: "8"
gluster_version_minor: "0"

# tasks/os/debian/common.yml
gluster_apt_keys__to_merge:
  43607F0DC2F8238C:
    keyring: "gluster"
    url:
      "https://download.gluster.org/pub/gluster/\
      glusterfs/{{ gluster_version_major }}/rsa.pub"

# tasks/os/debian/common.yml
gluster_apt_repositories__to_merge:
  gluster:
    # amd64 and arm64 are the only archs available currently, so we use amd64
    repo:
      "deb https://download.gluster.org/pub/gluster/glusterfs/\
      {{ gluster_version_major }}/{{ gluster_version_major }}.\
      {{ gluster_version_minor }}/{{ ansible_distribution }}/\
      {{ ansible_distribution_version}}/amd64/apt \
      {{ ansible_distribution_release }} main"

# tasks/packages.yml
gluster_custom_packages__to_merge:
  lvm2: "present"
  xfsprogs: "present"
  glusterfs-server: "latest"
