# Copyright (c) 2020-present eyeo GmbH
#
# This module is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---

# roles/icinga/{server,web} integration
# roles/postgresql/server/tasks/main.yml
icinga_for_web_postgresql_hba_entries__to_merge:
  - type: "host"
    database: "{{ icinga_server_database_name }}"
    user: "{{ icinga_server_database_user }}"
    address: "{{ icinga_web_server_ipv4_address }}/32"
    auth_method: "md5"

# yamllint disable rule:line-length
# provision-icinga-servers.yml
icinga_server_custom_icinga_services:
  content:
    name: "content"
    service_definition: |
      {{ lookup('file', 'roles/monitoring-plugins/files/icinga-services/content.conf') }}
    assign:
      - "intersection({{ icinga_server_https_service_group | to_json }}, host.vars.ansible.groups)"
  http_response_time:
    name: "http-response-time"
    service_definition: |
      {{ lookup('file', 'roles/monitoring-plugins/files/icinga-services/http_response_time.conf') }}
    assign:
      - "intersection({{ icinga_server_http_service_group | to_json }}, host.vars.ansible.groups)"
  https_response_time:
    name: "https_response_time"
    service_definition: |
      {{ lookup('file', 'roles/monitoring-plugins/files/icinga-services/https_response_time.conf') }}
    assign:
      - "intersection({{ icinga_server_https_service_group | to_json }}, host.vars.ansible.groups)"
  http_port:
    name: "http-port"
    service_definition: |
      {{ lookup('file', 'roles/monitoring-plugins/files/icinga-services/http_port.conf') }}
    assign:
      - "intersection({{ icinga_server_http_service_group | to_json }}, host.vars.ansible.groups)"
  https_port:
    name: "http-port"
    service_definition: |
      {{ lookup('file', 'roles/monitoring-plugins/files/icinga-services/https_port.conf') }}
    assign:
      - "intersection({{ icinga_server_https_service_group | to_json }}, host.vars.ansible.groups)"
# ssl_cert:
#  name: "ssl-cert"
#  service_definition: |
#    {{ common_service_header }}
#    {{ lookup('file', 'roles/monitoring-plugins/files/icinga-services/ssl_cert.conf') }}
#  assign:
#    - "intersection({{ icinga_server_http_service_group | to_json }}, host.vars.ansible.groups)"

# provision-icinga-servers.yml
icinga_server_monitoring_plugins:
  check_content:
    command: "check_content"
    dest: "{{ icinga_server_plugin_directory }}"
    group: "root"
    owner: "root"
    mode: "0755"
    package: "curl"
    src: "files/plugins/check_content"
  check_http_response_time:
    command: "check_http_response_time"
    dest: "{{ icinga_server_plugin_directory }}"
    group: "root"
    owner: "root"
    mode: "0775"
    src: "files/plugins/check_http_response_time"
  check_https_response_time:
    command: "check_https_response_time"
    dest: "{{ icinga_server_plugin_directory }}"
    group: "root"
    owner: "root"
    mode: "0775"
    src: "files/plugins/check_https_response_time"
  check_port:
    command: "check_port"
    dest: "{{ icinga_server_plugin_directory }}"
    group: "root"
    owner: "root"
    mode: "0775"
    src: "files/plugins/check_port"
  check_ssl_cert:
    command: "check_ssl_cert"
    dest: "{{ icinga_server_plugin_directory }}"
    group: "root"
    owner: "root"
    mode: "0775"
    src: "files/plugins/check_ssl_cert"
