# Copyright (c) 2020-present eyeo GmbH
#
# This module is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---

# roles/icinga/{server,web} integration
# roles/postgresql/server/tasks/main.yml
icinga_for_web_postgresql_hba_entries__to_merge:
  - type: "host"
    database: "{{ icinga_server_database_name }}"
    user: "{{ icinga_server_database_user }}"
    address: "{{ icinga_web_server_ipv4_address }}/32"
    auth_method: "md5"

# provision-icinga-servers.yml
# yamllint disable rule:line-length
# yamllint disable rule:quoted-strings
# https://icinga.com/docs/icinga2/latest/doc/04-configuration/#servicesconf
# https://gitlab.com/eyeo/devops/utilities/monitoring-plugins/-/blob/master/templates/config/services/{{ item.key }}.conf
# https://www.monitoring-plugins.org/doc/man/check_by_ssh.html
eyeo_icinga_server_custom_icinga_services:
  bandwidth:
    name:
      "{{ icinga_service_bandwidth_name
        | default('bandwidth') }}"
    service_definition: |
      {{ lookup('template', "{{ icinga_monitoring_plugins_dir
                              | default('.examples/monitoring-plugins') }}/files/icinga-services/bandwidth.conf") }}
    options:
      "{{ icinga_global_service_options |
          combine(icinga_service_bandwidth_options | default({}) ) }}"
    assign:
      "{{ icinga_service_bandwidth_assign
        | default(['host.vars.ansible.os_family == \"Debian\"']) }}"
    ignore:
      "{{ icinga_service_bandwidth_ignore
        | default([]) }}"
  connections:
    name:
      "{{ icinga_service_connections_name
        | default('connections') }}"
    service_definition: |
      {{ lookup('template', "{{ icinga_monitoring_plugins_dir
                              | default('.examples/monitoring-plugins') }}/files/icinga-services/connections.conf") }}
    options:
      "{{ icinga_global_service_options |
          combine(icinga_service_connections_options | default({}) ) }}"
    assign:
      "{{ icinga_service_connections_assign
        | default(['host.vars.ansible.system == \"Linux\"']) }}"
    ignore:
      "{{ icinga_service_connections_ignore
        | default([]) }}"
  http_port:
    name:
      "{{ icinga_service_http_port_name
        | default('http-port') }}"
    service_definition: |
      {{ lookup('template', "{{ icinga_monitoring_plugins_dir
                              | default('.examples/monitoring-plugins') }}/files/icinga-services/port.conf") }}
    options:
      "{{ icinga_global_service_options |
          combine(icinga_service_http_port_options | default({}) ) }}"
    assign:
      - "intersection({{ icinga_http_port_check_group
                       | default(icinga_server_http_service_group)
                       | to_json }},
                      host.vars.ansible.groups)"
    ignore:
      "{{ icinga_service_http_port_ignore
        | default([]) }}"
  http_response_time:
    name:
      "{{ icinga_service_http_response_time_name
        | default('http-response-time') }}"
    service_definition: |
      {{ lookup('template', '{{ icinga_server_base_dir }}/templates/config/services/response_time.conf' ) }}
    options:
      "{{ icinga_global_service_options |
          combine(icinga_service_http_response_time_options | default({}) ) }}"
    assign:
      - "intersection({{ icinga_http_response_time_check_group
                       | default(icinga_server_http_service_group)
                       | to_json }},
                      host.vars.ansible.groups)"
    ignore:
      "{{ icinga_service_http_response_time_ignore
        | default([]) }}"
  https_port:
    name:
      "{{ icinga_service_https_port_name
        | default('https-port') }}"
    service_definition: |
      {{ lookup('template', "{{ icinga_monitoring_plugins_dir
                              | default('.examples/monitoring-plugins') }}/files/icinga-services/port.conf",
         template_vars=dict(monitoring_plugins_port=443) ) }}
    options:
      "{{ icinga_global_service_options |
          combine(icinga_service_https_port_options | default({}) ) }}"
    assign:
      - "intersection({{ icinga_https_port_check_group
                       | default(icinga_server_https_service_group)
                       | to_json }},
                      host.vars.ansible.groups)"
    ignore:
      "{{ icinga_service_https_port_ignore
        | default([]) }}"
  https_response_time:
    name:
      "{{ icinga_service_https_response_time_name
        | default('https-response-time') }}"
    service_definition: |
      {{ lookup('template', '{{ icinga_server_base_dir }}/templates/config/services/response_time.conf',
                 template_vars=dict(monitoring_plugins_response_time_ssl=1) ) }}
    options:
      "{{ icinga_global_service_options |
          combine(icinga_service_https_response_time_options | default({}) ) }}"
    assign:
      - "intersection({{ icinga_https_response_time_check_group
                       | default(icinga_server_https_service_group)
                       | to_json }},
                      host.vars.ansible.groups)"
    ignore:
      "{{ icinga_service_https_response_time_ignore
        | default([]) }}"
  memory:
    name:
      "{{ icinga_service_memory_name
        | default('memory') }}"
    service_definition: |
      {{ lookup('template', "{{ icinga_monitoring_plugins_dir
                              | default('.examples/monitoring-plugins') }}/files/icinga-services/memory.conf") }}
    options:
      "{{ icinga_global_service_options |
          combine(icinga_service_memory_options | default({}) ) }}"
    assign:
      "{{ icinga_service_memory_assign
        | default(['host.vars.ansible.system == \"Linux\"']) }}"
    ignore:
      "{{ icinga_service_memory_ignore
        | default([]) }}"
  raid:
    name:
      "{{ icinga_service_raid_name
        | default('raid') }}"
    service_definition: |
      {{ lookup('template', "{{ icinga_monitoring_plugins_dir
                              | default('.examples/monitoring-plugins') }}/files/icinga-services/raid.conf") }}
    options:
      "{{ icinga_global_service_options |
          combine(icinga_service_raid_options | default({}) ) }}"
    assign:
      "{{ icinga_service_raid_assign
        | default(['host.vars.ansible.system == \"Linux\"']) }}"
    ignore:
      "{{ icinga_service_raid_ignore
        | default([]) }}"
  ssl_cert:
    name:
      "{{ icinga_service_ssl_cert_name
        | default('ssl-cert') }}"
    service_definition: |
      {{ lookup('template', '{{ icinga_server_base_dir }}/templates/config/services/ssl_cert.conf') }}
    options:
      "{{ icinga_global_service_options |
          combine(icinga_service_ssl_cert_options | default({}) ) }}"
    assign:
      - "intersection({{ icinga_ssl_cert_check_group
                       | default(icinga_server_https_service_group)
                       | to_json }},
                      host.vars.ansible.groups)"
    ignore:
      "{{ icinga_service_ssl_cert_ignore
        | default([]) }}"
  systemd_postgresql:
    name:
      "{{ icinga_service_systemd_postgresql_name
        | default('systemd_postgresql') }}"
    service_definition: |
      {{ lookup('template', "{{ icinga_monitoring_plugins_dir
                              | default('.examples/monitoring-plugins') }}/files/icinga-services/systemd_postgresql.conf") }}
    options:
      "{{ icinga_global_service_options |
          combine(icinga_service_systemd_postgresql_options | default({}) ) }}"
    assign:
      - "intersection({{ icinga_systemd_postgresql_check_group
                       | default([\"postgresql-servers\"])
                       | to_json }},
                      host.vars.ansible.groups)"
    ignore:
      "{{ icinga_service_systemd_postgresql_ignore
        | default([]) }}"
  zombie_procs:
    name:
      "{{ icinga_service_zombie_procs_name
        | default('zombie-processes') }}"
    service_definition: |
      {{ lookup('template', "{{ icinga_monitoring_plugins_dir
                              | default('.examples/monitoring-plugins') }}/files/icinga-services/zombie_procs.conf") }}
    options:
      "{{ icinga_global_service_options |
          combine(icinga_service_zombie_procs_options | default({}) ) }}"
    assign:
      "{{ icinga_service_zombie_procs_assign
        | default(['host.vars.ansible.system == \"Linux\"']) }}"
    ignore:
      "{{ icinga_service_zombie_procs_ignore
        | default([]) }}"
# yamllint enable rule:line-length
# yamllint enable rule:quoted-strings

# provision-icinga-servers.yml
eyeo_icinga_server_custom_icinga_users:
  noc:
    import:
      - "generic-user"
    display_name: "eyeo NOC"
    email: "{{ eyeo_icinga_server_custom_icinga_user_email }}"
    groups:
      - "noc"

# provision-icinga-servers.yml
eyeo_icinga_server_custom_icinga_user_groups:
  noc:
    display_name: "eyeo NOC"

# provision-icinga-servers.yml
eyeo_icinga_server_custom_icinga_notifications:
  mail-hourly:
    command: "mail-service-notification"
    interval: "1h"
    user_groups:
      - "noc"
    states: # excludes Warning
      - "Critical"
      - "Unknown"
      - "OK"
    types: # exclude mundane ones
      - "Problem"
      - "Recovery"
    assign:
      - "service.name == \"ping4\""
      - "service.name == \"ssh\""
      - "service.name == \"icinga\""
      - "service.name == \"http_port\""
      - "service.name == \"https_port\""
  mail-daily:
    command: "mail-service-notification"
    name: "mail-daily"
    interval: "24h"
    user_groups:
      - "noc"
    states: # exclude Unknown
      - "Critical"
      - "Warning"
      - "OK"
    assign:
      - "service.name == \"ping6\""
      - "service.name == \"load\""
      - "service.name == \"disk\""
      - "service.name == \"raid\""
      - "service.name == \"memory\""
      - "service.name == \"swap\""
      - "service.name == \"http_response_time\""
      - "service.name == \"https_response_time\""
      - "service.name == \"connections\""
      - "service.name == \"users\""
      - "service.name == \"bandwidth\""
  mail-weekly:
    command: "mail-service-notification"
    name: "mail-weekly"
    interval: "168h"
    user_groups:
      - "noc"
    states: # exclude all other than Critical
      - "Critical"
    types: # exclude all other than Problem
      - "Problem"
    assign:
      - "service.name == \"needrestart\""
      - "service.name == \"processes\""
      - "service.name == \"zombie_procs\""
      - "service.name == \"ssl_cert\""
      - "service.name == \"apt\""
