# Copyright (c) 2020-present eyeo GmbH
#
# This module is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---

# provision-icinga-web-servers.yml
# roles/icinga/web/defaults/main.yml
icinga_web_httpd_handlers:
  - "service : apache2"

# https://httpd.apache.org/docs/current/mod/
# roles/apache2/tasks/main.yml
icinga_web_apache2_modules__to_merge:
  # TODO: this one could be loaded by tasks/apache2-php-fpm.yml itself
  proxy_fcgi:
    state: "enabled"
  rewrite:
    state: "enabled"
  setenvif:
    state: "enabled"

# roles/postgresql/tasks/main.yml
icinga_web_postgresql_databases__to_merge:
  "{{ icinga_web_database_name }}":
    name: "{{ icinga_web_database_name }}"
    owner: "{{ icinga_web_database_user }}"
    encoding: "UTF8"
icinga_web_postgresql_users__to_merge:
  "{{ icinga_web_database_user }}":
    name: "{{ icinga_web_database_user }}"
    password: "{{ icinga_web_database_password }}"
    role_attr_flags: "SUPERUSER"
