# Copyright (c) 2020-2023 eyeo GmbH
#
# This module is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---

# roles/icinga/{server,web} integration
# roles/postgresql/server/tasks/main.yml
icinga_for_web_postgresql_hba_entries__to_merge:
  - type: "host"
    database: "{{ icinga_server_database_name }}"
    user: "{{ icinga_server_database_user }}"
    address: "{{ icinga_web_server_ipv4_address }}/32"
    auth_method: "md5"

# provision-icinga-servers.yml
# yamllint disable rule:line-length
eyeo_icinga_server_custom_icinga_services:
  systemd_postgresql:
    name: "systemd_postgresql"
    service_definition: |
      {{ lookup('template', 'roles/monitoring-plugins/files/icinga-services/systemd_postgresql.conf') }}
    assign:
      - "intersection([\"postgresql-servers\"], host.vars.ansible.groups)"
# yamllint enable rule:line-length

# provision-icinga-servers.yml
eyeo_icinga_server_custom_icinga_users:
  noc:
    import:
      - "generic-user"
    display_name: "eyeo NOC"
    email: "{{ eyeo_icinga_server_custom_icinga_user_email }}"
    groups:
      - "noc"

# provision-icinga-servers.yml
eyeo_icinga_server_custom_icinga_user_groups:
  noc:
    display_name: "eyeo NOC"

# provision-icinga-servers.yml
eyeo_icinga_server_custom_icinga_notifications:
  mail-hourly:
    command: "mail-service-notification"
    interval: "1h"
    user_groups:
      - "noc"
    states: # excludes Warning
      - "Critical"
      - "Unknown"
      - "OK"
    types: # exclude mundane ones
      - "Problem"
      - "Recovery"
    assign:
      - "service.name == \"ping4\""
      - "service.name == \"ssh\""
      - "service.name == \"icinga\""
      - "service.name == \"http_port\""
      - "service.name == \"https_port\""
  mail-daily:
    command: "mail-service-notification"
    name: "mail-daily"
    interval: "24h"
    user_groups:
      - "noc"
    states: # exclude Unknown
      - "Critical"
      - "Warning"
      - "OK"
    assign:
      - "service.name == \"ping6\""
      - "service.name == \"load\""
      - "service.name == \"disk\""
      - "service.name == \"raid\""
      - "service.name == \"memory\""
      - "service.name == \"swap\""
      - "service.name == \"http_response_time\""
      - "service.name == \"https_response_time\""
      - "service.name == \"connections\""
      - "service.name == \"users\""
      - "service.name == \"bandwidth\""
  mail-weekly:
    command: "mail-service-notification"
    name: "mail-weekly"
    interval: "168h"
    user_groups:
      - "noc"
    states: # exclude all other than Critical
      - "Critical"
    types: # exclude all other than Problem
      - "Problem"
    assign:
      - "service.name == \"needrestart\""
      - "service.name == \"processes\""
      - "service.name == \"zombie_procs\""
      - "service.name == \"ssl_cert\""
      - "service.name == \"apt\""
