# Copyright (c) 2025 Josip Rodin
#
# This module is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---

# group_vars/k8s-cluster-init.yml
kubelet_configuration__to_merge:
  - name: "metrics"
    yaml: |
      serverTLSBootstrap: true

k8s_cluster_init_kubelet_csr_sign_custom_paths__to_merge:
  "{{ k8s_cluster_config_server_dir }}/kubeadm/approve-kubelet-serving-csr.sh":
    dest: "{{ k8s_cluster_config_server_dir }}/kubeadm/approve-kubelet-serving-csr.sh"
    state: "copy"
    content: |
      {{ kubectl_command }} get csr -o json | \
        jq -r '.items[] | select(.spec.signerName == "kubernetes.io/kubelet-serving") | .metadata.name' | \
        xargs -r \
          {{ kubectl_command }} certificate approve

# TODO: verify first if there is a join group?
k8s_cluster_init_kubelet_csr_sign_custom_shells__to_merge:
  k8s_01_cluster_14_approve_kubelet_serving_csr:
    cmd: |
      sh /var/local/kubeadm/approve-kubelet-serving-csr.sh

# group_vars/k8s-helm-releases.yml
k8s_cluster_init_metrics_k8s_helm_releases__to_merge:
  - name: "metrics-server"
    repo: "metrics-server"
    chart: "metrics-server"
    repo_url: "https://kubernetes-sigs.github.io/metrics-server/"
    namespace: "metrics-server"
    create_namespace: true
