# Copyright (c) 2021-2023 eyeo GmbH
#
# This module is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---

# tasks/packages.yml
munin_server_custom_packages__to_merge:
  munin: "present"
  libcgi-fast-perl: "present"
  bsd-mailx: "present"
  cron: "present"
  logrotate: "present"

# tasks/paths.yml
munin_server_ssh_keys_dirs_custom_paths__to_merge:
  /var/lib/munin/.ssh:
    state: "directory"
    owner: "munin"
    group: "munin"
    mode: "0700"

munin_server_ssh_key_path:
  "/var/lib/munin/.ssh/id_ed25519"

# tasks/ssh-keys.yml
munin_server_custom_ssh_keys__to_merge:
  # NB: this is later copied into group_vars/munin-node-hosts.yml
  default:
    dest: "{{ munin_server_ssh_key_path }}"
    type: "ed25519"
    size: 521
    owner: "munin"
    group: "munin"

# run update with 60s update_rate
munin_update_schedule:
  "* * * * *"
# run limits less often, as this triggers notifications
munin_limits_schedule:
  "*/5 * * * *"
# run html even less often, as this is resource-intensive yet often no-op
munin_html_schedule:
  "*/10 * * * *"

munin_update_global_timeout:
  "55"

munin_update_rate_settings_bullseye: |
  timeout_fetch_all_nodes 45
  timeout_fetch_one_node 40

# yamllint disable rule:line-length
munin_update_rate_settings: |
  update_rate 60 # seconds
  ssh_options -o ChallengeResponseAuthentication=no -o StrictHostKeyChecking=no -o ConnectTimeout=5
  {{ (ansible_distribution == 'Debian' and ansible_distribution_version|int > 10)
     | ternary(munin_update_rate_settings_bullseye, '')
  }}
# yamllint enable rule:line-length

munin_update_rate_plugin_settings: |
    munin_stats.update.warning 0:46
    munin_stats.update.critical 0:56

# tasks/paths.yml
munin_server_config_custom_paths__to_merge:
  # NB: Debian package conffile we override
  /etc/cron.d/munin:
    # yamllint disable rule:line-length
    content: |
      MAILTO=root
      # this re-implements /usr/bin/munin-cron in a more fine-grained manner
      {{ munin_update_schedule }}     munin /usr/share/munin/munin-update --timeout={{ munin_update_global_timeout }}
      {{ munin_limits_schedule }}     munin /usr/share/munin/munin-limits
      {{ munin_html_schedule }}    munin nice /usr/share/munin/munin-html

      # remove stale generated html and graph files (e.g. disabled plugins or fields with volatile names)
      27 03 * * *     munin htmldir=$({ cat /etc/munin/munin.conf /etc/munin/munin-conf.d/* 2>/dev/null || true; } | sed -nE 's/^\s*htmldir\s+(\S.*)$/\1/p' | tail -1); htmldir=${htmldir:-/var/cache/munin/www}; if [ -d "$htmldir" ]; then find "$htmldir/" -type f -name "*.html" -mtime +30 -delete; find "$htmldir/" -mindepth 1 -type d -empty -delete; fi
      32 03 * * *     www-data cgitmpdir=$({ cat /etc/munin/munin.conf /etc/munin/munin-conf.d/* 2>/dev/null || true; } | sed -nE 's/^\s*cgitmpdir\s+(\S.*)$/\1/p' | tail -1); cgitmpdir=${cgitmpdir:-/var/lib/munin/cgi-tmp}; if [ -d "$cgitmpdir" ]; then find "$cgitmpdir/" -type f -mtime +1 -delete; find "$cgitmpdir/" -mindepth 1 -type d -empty -delete; fi
    # yamllint enable rule:line-length
    mode: "0644"
    state: "copy"
  /etc/munin/munin-conf.d/aaa-munin.conf:
    # yamllint disable rule:line-length
    content: |
      graph_strategy cgi
      munin_cgi_graph_jobs {{ munin_cgi_graph_jobs }}
      max_processes {{ munin_max_processes }}

      {{ munin_update_rate_settings }}

      graph_data_size custom 1d, 5m for 1w, 15m for 1y, 1h for 5y
      contact.email.command mail -s "${var:group}/${var:host} ${var:graph_title}" {{ munin_contact_email }}
      contact.log.command tee -a /var/log/munin/alert.log >/dev/null
    # yamllint enable rule:line-length
    mode: "0644"
    state: "copy"

# provision-munin-node-hosts.yml
munin_server_munin_node_paths__to_merge:
  # munin_stats gets automatically enabled, but this more detailed graph doesn't
  /etc/munin/plugins/munin_update:
    src: "/usr/share/munin/plugins/munin_update"
    state: "link"
    notify:
      - "service : munin-node"
      - "service : munin-async"

# tasks/paths.yml
munin_server_self_definition_custom_paths__to_merge:
  # TODO: kill localhost in /etc/munin/munin.conf
  "/etc/munin/munin-conf.d/{{ inventory_hostname_short }}.conf":
    dest: "/etc/munin/munin-conf.d/{{ inventory_hostname_short }}.conf"
    content: |
      [{{ inventory_hostname }}]
        address ssh://munin-async@{{ inventory_hostname }}
      # match update_rate @ aaa-munin.conf
        {{ munin_update_rate_plugin_settings | indent(2) }}
      # omit disabled graph
        munin_stats.graph.graph no
      # these notifications are annoying and repetitive
        munin_stats.contacts no
        munin_update.contacts no
    mode: "0644"
    state: "copy"

# tasks/commands.yml
munin_server_custom_commands__to_merge:
  prerequisite_to_munin_cgi_graph:
    cmd: "/usr/share/munin/munin-update"
    creates: "/var/lib/munin/datafile"
    become_user: "munin"

# tasks/services.yml
munin_server_custom_services__to_merge:
  munin-cgi-graph:
    enabled: true
    state: "started"
    content: |
      [Unit]
      Description=Munin CGI Graph service
      Requires=munin-cgi-graph.socket
      After=network.target

      [Service]
      Type=simple
      Environment=CGI_DEBUG={{ munin_cgi_graph_debug }}
      User=www-data
      Group=www-data
      ExecStart=/usr/lib/munin/cgi/munin-cgi-graph
      StandardInput=socket
      StandardOutput=null
      StandardError=syslog

      [Install]
      WantedBy=multi-user.target
  munin-cgi-graph.socket:
    name: "munin-cgi-graph"
    type: "socket"
    enabled: true
    state: "started"
    content: |
      [Unit]
      Description=Munin CGI Graph socket

      [Socket]
      SocketUser=www-data
      SocketGroup=www-data
      SocketMode=0600
      ListenStream=/var/run/munin/fastcgi-graph.sock

      [Install]
      WantedBy=sockets.target

# roles/apache2/tasks/main.yml
# provision-apache2-servers.yml
munin_server_apache2_modules__to_merge:
  proxy_fcgi: &apache2_standard_module
    package: false

munin_server_apache2_site_config: |
  Alias /munin/static/ /etc/munin/static/
  <Directory /etc/munin/static>
    Require all granted
  </Directory>
  # requires munin-html cron jobs
  Alias /munin/ /var/cache/munin/www/
  <Directory /var/cache/munin/www/>
    {{ munin_server_auth_settings }}
  </Directory>
  # precludes munin-graph cron jobs
  ScriptAlias /munin-cgi/ /usr/lib/munin/cgi/
  <Directory /usr/lib/munin/cgi>
    {{ munin_server_auth_settings }}
  </Directory>
  <Location ~ ^/munin-cgi/munin-cgi-graph/>
    SetHandler "proxy:unix:/var/run/munin/fastcgi-graph.sock|fcgi://localhost/"
  </Location>
