# Copyright (c) 2020-present eyeo GmbH
#
# This module is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---

# tasks/packages.yml
munin_custom_packages__to_merge:
  munin-node: "present"
  munin-plugins-extra: "present"
  munin-async: "present"
  patch: "present"

munin_server_from_rule:
  "{{ munin_server_from_host_list | join(',') }}"

# tasks/authorized-keys.yml
munin_async_custom_authorized_keys__to_merge:
  munin-async:
    user: "munin-async"
    key_options:
      - 'from="{{ munin_server_from_rule }}"'
      - 'command="/usr/share/munin/munin-async --spoolfetch"'
      - "no-agent-forwarding"
      - "no-port-forwarding"
      - "no-pty"
      - "no-X11-forwarding"
      - "no-user-rc"
    key: "{{ munin_server_ssh_key }}"

# minrate reduce from default 300->60 to match munin update_rate 60
# verbose so we see what's going on
# interval/retain reduce from default 86400/7 -> 300/5 so that
# we spend less disk space on nodes
munin_asyncd_parameters:
  "--verbose --minrate 60 --interval 300 --retain 5"

munin_asyncd_plugin_update_rate_patches:
  jessie: &munin_asyncd_pre_bullseye_patch # 2.0.25
    "files/munin-asyncd.plugin_update_rate.patch"
  stretch: # 2.0.33
    *munin_asyncd_pre_bullseye_patch
  bionic: # 2.0.37
    *munin_asyncd_pre_bullseye_patch
  stretch-backports: # 2.0.49
    *munin_asyncd_pre_bullseye_patch
  buster: # 2.0.49
    *munin_asyncd_pre_bullseye_patch
  focal: # 2.0.56
    *munin_asyncd_pre_bullseye_patch
  buster-backports: &munin_asyncd_bullseye_patch # 2.0.67
    "files/munin-asyncd.plugin_update_rate.2.0.67.patch"
  bullseye: # 2.0.67
    *munin_asyncd_bullseye_patch

# yamllint disable rule:line-length
debian_family_backports_selector:
  "{{ ansible_distribution_release +
      (apt_enable_debian_backports is defined and
       apt_enable_debian_backports == 'true' and
       munin_asyncd_plugin_update_rate_patches[ansible_distribution_release + '-backports'] is defined)
      | ternary('-backports', '')
    }}"

munin_asyncd_plugin_update_rate_patch:
  "{{ munin_asyncd_plugin_update_rate_patches[debian_family_backports_selector] }}"
# yamllint enable rule:line-length

# provision-munin-node-hosts.yml
munin_async_systemd_munin_node_paths__to_merge:
  /etc/systemd/system/munin-async.service.d:
    state: "directory"
  /etc/systemd/system/munin-async.service.d/override.conf:
    state: "copy"
    content: |
      [Service]
      ExecStart=
      ExecStart=/usr/share/munin/munin-asyncd {{ munin_asyncd_parameters }}
    mode: "0644"
    notify:
      - "systemd : daemon-reload"
      - "service : munin-async"

# provision-munin-node-hosts.yml
munin_node_service_state:
  "{{ munin_node_service_enabled | ternary('started', 'stopped') }}"
munin_node_service_strategy:
  "restart"
munin_async_service_state:
  "{{ munin_async_service_enabled | ternary('started', 'stopped') }}"
munin_async_service_strategy:
  "restart"
