# Copyright (c) 2019-2023 eyeo GmbH
#
# This module is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---

# by default we tune only the stuff that doesn't require a hard restart,
# and we position it at the start of the sort queue so host vars can override it
aa_default_postgresql_config__to_merge:
  # to diagnose slow queries, log them
  log_min_duration_statement: "1000"
  # wordy, but better for security audits
  log_connections: "on"
  # adds application_name %a field to the default
  log_line_prefix: "'%m [%p] %q%u@%d %a '"
