# Copyright (c) 2023-present eyeo GmbH
#
# This module is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---

testpages_repo:
  "https://gitlab.com/eyeo/developer-experience/testpages.adblockplus.org"

# provision-eyeo-cms-web-servers.yml
testpages_eyeo_cms_content_repos__to_merge:
  "{{ testpages_primary_domain }}":
    name: "{{ testpages_primary_domain }}"
    repo: "{{ testpages_repo }}"
    version: "{{ testpages_version }}"
  "{{ testpages_secondary_domain }}":
    name: "{{ testpages_secondary_domain }}"
    repo: "{{ testpages_repo }}"
    version: "{{ testpages_version }}"

# roles/apache2/tasks/main.yml
# provision-apache2-servers.yml
testpages_apache2_modules__to_merge:
  ssl: &apache2_standard_module
    package: false

# this subdomain -> domain document root link exists because we implement
# rebuilds through virtual host settings, and there's no need for a third
# build just because of the subdomain
# tasks/commands.yml
testpages_subdomain_custom_commands__to_merge:
  prepare_subdomain_document_root:
    cmd: "ln -s {{ testpages_secondary_domain }}
                /var/www/{{ testpages_secondary_subdomain }}"
    creates: "/var/www/{{ testpages_secondary_subdomain }}"

# roles/eyeo/sitescripts/tasks/main.yml
testpages_sitescripts_ini_settings__to_merge:
  - section: "multiplexer"
    key: "sitescripts.testpages.web.sitekey_frame"
    value: ""
  - section: "testpages"
    key: "sitekeyFrameTemplate"
    value: "/var/www/{{ testpages_secondary_domain }}/sitekey_frame.tmpl"
  - section: "testpages"
    key: "sitekeyPath"
    value: "/var/www/{{ testpages_secondary_domain }}/site.key"

# tasks/paths.yml
# sitescripts/testpages/web/sitekey_frame.py imports M2Crypto
testpages_sitekey_frame_custom_packages__to_merge:
  python3-m2crypto: "present"

# yamllint disable rule:line-length
testpages_sitescripts_extra_apache_config: |
  # this part is supported by sitescripts-multiplexer
  <Location /sitekey-frame>
    ProxyFCGISetEnvIf "reqenv('PATH_INFO') !~ m|/sitekey-frame|" PATH_INFO "/sitekey-frame"
    SetHandler "proxy:unix:{{ sitescripts_multiplexer_socket_path }}|fcgi://localhost/"
  </Location>
# yamllint enable rule:line-length

# task/paths.yml
testpages_deploy_custom_paths__to_merge:
  /etc/sudoers.d/deploy_testpages:
    state: "copy"
    mode: "0440"
    content: |
      Defaults:gitlab-runner env_keep += "CI_COMMIT_REF_SLUG"
      gitlab-runner ALL=(root) NOPASSWD: /usr/local/sbin/deploy_testpages
      gitlab-runner ALL=(root) NOPASSWD: /usr/local/sbin/undeploy_testpages
    validate:
      "/usr/sbin/visudo --check --file=%s"
  /usr/local/sbin/deploy_testpages:
    state: "copy"
    mode: "0755"
    src: "files/testpages/deploy_testpages"
  /usr/local/sbin/undeploy_testpages:
    state: "copy"
    mode: "0755"
    src: "files/testpages/undeploy_testpages"
