# Copyright (c) 2018-present eyeo GmbH
#
# This module is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/lineinfile_module.html
- name:
    "apt : stable keyword check"
  lineinfile:
    path: "/etc/apt/sources.list"
    regexp: "^deb(-src)?.* stable.*$"
    state: "absent"
  check_mode:
    true
  changed_when:
    false
  register:
    "apt_sources_list_stable"

# https://docs.ansible.com/ansible/latest/modules/fail_module.html
- fail:
    msg: >-
      Found {{ apt_sources_list_stable.found }} occurences of the 'stable'
      keyword in apt sources.list files. Replace this with the distribution
      codename and try again.
  when:
    "apt_sources_list_stable.found"

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/lineinfile_module.html
- name:
    "apt : security source check"
  lineinfile:
    path: "/etc/apt/sources.list"
    regexp: "security\\.debian\\.org"
    state: "absent"
  check_mode:
    true
  changed_when:
    false
  register:
    "apt_sources_list_security"

# https://docs.ansible.com/ansible/latest/modules/fail_module.html
- fail:
    msg: >-
      Couldn't find security.debian.org in apt sources.list file.
      Please add it and try again.
  when:
    "not apt_sources_list_security.found"

# action_plugins/merge_variable.py
# https://docs.ansible.com/ansible/latest/modules/apt_key_module.html
- name:
    "merge_variable : apt_keys"
  merge_variable:
    default: {}
    name: "apt_keys"
    suffix: "apt_keys__to_merge"

# https://docs.ansible.com/ansible/latest/modules/apt_repository_module.html
- name:
    "merge_variable : apt_repositories"
  merge_variable:
    default: {}
    name: "apt_repositories"
    suffix: "apt_repositories__to_merge"

# https://docs.ansible.com/ansible/latest/modules/copy_module.html
- name:
    "merge_variable : apt_preferences"
  merge_variable:
    default: {}
    name: "apt_preferences"
    suffix: "apt_preferences__to_merge"

# https://gitlab.com/eyeo/devops/ansible-playbooks/tree/master/roles/apt
- import_role:
    name: "apt"
