# Copyright (c) 2019-present eyeo GmbH
#
# This module is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---

.vagrantjob:
  variables:
    GIT_STRATEGY: "clone"
    GIT_SUBMODULE_STRATEGY: "recursive"
    VAGRANT_PROVIDER: "libvirt"
    # FIXME pre-fetch the actual box from Vagrant config for the
    # specific test host, or default
    VAGRANT_BOX: "debian/buster64"
  tags:
    - "eyeo-devops-ansible-playbooks-vagrant-1"
  before_script:
    - "vagrant box list | grep -q $VAGRANT_BOX || \
       vagrant box add --provider libvirt $VAGRANT_BOX"
    - "vagrant destroy $TEST_HOST -f || true"
  script:
    - "git checkout -b $CI_COMMIT_REF_NAME"
    - "vagrant up --provider=$VAGRANT_PROVIDER $TEST_HOST"
  after_script:
    - "vagrant destroy $TEST_HOST -f"
  stage:
    "vagrant"
  retry:
    max: 2
    when:
      - "always"
