# Copyright (c) 2019-2023 eyeo GmbH
#
# This module is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---

.vagrantshortlivedjob:
  variables:
    GIT_STRATEGY: "clone"
    GIT_SUBMODULE_STRATEGY: "recursive"
    VAGRANT_PROVIDER: "libvirt"
    # FIXME pre-fetch the actual box from Vagrant config for the
    # specific test host, or default
    VAGRANT_BOX: "debian/buster64"
  tags:
    - "eyeo-devops-ansible-playbooks-vagrant-shortlived-1"
  before_script:
    - |
      set -x
      vagrant box list | grep -q $VAGRANT_BOX || \
        vagrant box add --provider $VAGRANT_PROVIDER $VAGRANT_BOX
      if ! vagrant destroy $TEST_HOST -f; then
        if [ "$VAGRANT_PROVIDER" = "libvirt" ]; then
          libvirt_vm=ansible-playbooks_$TEST_HOST
          export LIBVIRT_DEFAULT_URI="qemu:///system"
          virsh destroy $libvirt_vm || true
          virsh undefine $libvirt_vm --remove-all-storage
        else
          echo "Aiee, $TEST_HOST could not be destroyed in $VAGRANT_PROVIDER"
          exit 1
        fi
      fi
      set +x
    - |
      if [ -n "$VAGRANT_BOX_NEEDS_CHECKED_OUT_BRANCH" ]; then
         echo "Box |$VAGRANT_BOX_NEEDS_CHECKED_OUT_BRANCH| needs a branch"
         git checkout -b $CI_COMMIT_REF_NAME
      fi
  script:
    - "vagrant up --provider=$VAGRANT_PROVIDER $TEST_HOST"
  after_script:
    - "vagrant destroy $TEST_HOST -f"
  stage:
    "vagrant-shortlived"
  retry:
    max: 1
    when:
      - "always"
  resource_group:
    "eyeo-devops-ansible-playbooks-vagrant-shortlived-1/$TEST_HOST"
