#!/bin/sh -ex
# modeled after ansible-playbooks tasks/eyeo-cms.yml deploy_eyeo_cms_web_*

DOMAIN="{{ secondary_testpages_domain }}"
SUBDOMAIN="{{ secondary_testpages_subdomain }}"
test -n "$DOMAIN" || exit 1
test -n "$SUBDOMAIN" || exit 1
user="www"
id "$user" || exit 2
SOURCE_DIR=$1
test -d "$SOURCE_DIR" || exit 3
dest_dir="/var/www"
test -d "$dest_dir" || exit 4
if [ "$CI_COMMIT_REF_SLUG" = "master" ]; then
  final_dest_dir=$dest_dir/$DOMAIN
else
  final_dest_dir=$dest_dir/$CI_COMMIT_REF_SLUG.$DOMAIN
fi
sudo install -d -o $user $final_dest_dir
sudo -u $user rsync -aHAX --del -vP --stats $SOURCE_DIR/ $final_dest_dir/
# NB: this per-branch logic doesn't actually work
if [ $CI_COMMIT_REF_SLUG != "master" ]; then
  base_virtual_host_file=/etc/apache2/sites-available/$DOMAIN.conf
  base_virtual_host_file_ssl=/etc/apache2/sites-available/$DOMAIN-ssl.conf
  subdomain_virtual_host_file=/etc/apache2/sites-available/$SUBDOMAIN.conf
  subdomain_virtual_host_file_ssl=/etc/apache2/sites-available/$SUBDOMAIN-ssl.conf
  test -e "$base_virtual_host_file" || exit 5
  sed -e s,$DOMAIN,$CI_COMMIT_REF_SLUG.$DOMAIN,g \
      $base_virtual_host_file | \
    sudo tee /etc/apache2/sites-available/$CI_COMMIT_REF_SLUG.$DOMAIN.conf
  if [ -e $base_virtual_host_file_ssl ]; then
  sed -e s,$DOMAIN,$CI_COMMIT_REF_SLUG.$DOMAIN,g \
      $base_virtual_host_file_ssl | \
    sudo tee /etc/apache2/sites-available/$CI_COMMIT_REF_SLUG.$DOMAIN-ssl.conf
  fi
  sed -e s,$SUBDOMAIN,$CI_COMMIT_REF_SLUG.$SUBDOMAIN,g \
      $subdomain_virtual_host_file | \
    sudo tee /etc/apache2/sites-available/$CI_COMMIT_REF_SLUG.$SUBDOMAIN.conf
  sed -e s,$SUBDOMAIN,$CI_COMMIT_REF_SLUG.$SUBDOMAIN,g \
      $subdomain_virtual_host_file | \
    sudo tee /etc/apache2/sites-available/$CI_COMMIT_REF_SLUG.$SUBDOMAIN-ssl.conf
  sudo a2ensite $CI_COMMIT_REF_SLUG.$DOMAIN.conf
  if [ -e $base_virtual_host_file_ssl ]; then
  sudo a2ensite $CI_COMMIT_REF_SLUG.$DOMAIN-ssl.conf
  fi
  sudo a2ensite $CI_COMMIT_REF_SLUG.$SUBDOMAIN.conf
  sudo a2ensite $CI_COMMIT_REF_SLUG.$SUBDOMAIN-ssl.conf
  sudo service apache2 status
  sudo service apache2 reload
fi
