# Copyright (c) 2020-present eyeo GmbH
#
# This module is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---

# https://docs.ansible.com/ansible/latest/modules/apt_module.html
- name:
    "apt : jdk_package_name"
  apt:
    cache_valid_time: "{{ apt_cache_valid_time | default(omit) }}"
    default_release: "{{ apt_default_release | default(omit) }}"
    name: "{{ jdk_package_name | default('default-jdk') }}"
    state: "present"
    update_cache: "{{ apt_update_cache | default(omit) }}"
  become:
    true

# https://docs.ansible.com/ansible/latest/copy_module.html
- name:
    "copy : /usr/local/bin/apk_signer"
  copy:
    dest: "/usr/local/bin/apk_signer"
    mode: "0755"
    src: "files/apk_signer"
    validate:
      "/bin/sh -n %s"
  become:
    true

# https://docs.ansible.com/ansible/latest/copy_module.html
- name:
    "copy : /etc/sudoers.d/{{ item.key }}"
  copy:
    dest: "/etc/sudoers.d/{{ item.key }}"
    mode: "0440"
    content: |
      {{ item.key }} ALL=(ALL) NOPASSWD:/usr/bin/jarsigner
    validate:
      "/usr/sbin/visudo --check --file=%s"
  become:
    true
  loop_control:
    label: "{{ item.key }}"
  with_dict:
    "{{ signing_users | mandatory }}"

# https://docs.ansible.com/ansible/latest/modules/file_module.html
- name:
    "file: /home/{{ item.key }}/.ssh"
  file:
    path: "/home/{{ item.key }}/.ssh"
    state: "directory"
    mode: "0700"
  become:
    true
  loop_control:
    label: "{{ item.key }}"
  with_dict:
    "{{ signing_users | mandatory }}"

# https://docs.ansible.com/ansible/latest/copy_module.html
- name:
    "copy : /home/{{ item.key }}/.ssh/environment"
  copy:
    dest: "/home/{{ item.key }}/.ssh/environment"
    mode: "0600"
    content: |
      APK_KEYSTORE_NAME={{ APK_KEYSTORE_NAME | mandatory }}
      APK_KEY_ALIAS_NAME={{ APK_KEY_ALIAS_NAME | mandatory }}
      APK_STOREPASS={{ APK_STOREPASS | mandatory }}
      APK_KEYPASS={{ APK_KEYPASS | mandatory }}
    validate:
      "/bin/sh -n %s"
    owner: "{{ item.key }}"
    group: "{{ item.key }}"
  become:
    true
  loop_control:
    label: "{{ item.key }}"
  with_dict:
    "{{ signing_users | mandatory }}"

# https://docs.ansible.com/ansible/latest/modules/blockinfile_module.html
- name:
    "blockinfile : .bashrc"
  blockinfile:
    path: "~{{ item.key }}/.bashrc"
    block: |
      export APK_KEYSTORE_NAME={{ APK_KEYSTORE_NAME | mandatory }}
      export APK_KEY_ALIAS_NAME={{ APK_KEY_ALIAS_NAME | mandatory }}
      export APK_STOREPASS={{ APK_STOREPASS | mandatory }}
      export APK_KEYPASS={{ APK_KEYPASS | mandatory }}
  loop:
    "{{ lookup('dict', signing_users | mandatory)
      | selectattr('value.local', 'defined')
      | selectattr('value.local', 'equalto', true)
      | list
      | sort(attribute='key')
      }}"
  loop_control:
    label: "{{ item.key }}"
  become: true
