# Copyright (c) 2020-present eyeo GmbH
#
# This module is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---

# https://docs.ansible.com/ansible/latest/modules/user_module.html
- name:
    "user : apk_signing_group_name"
  user:
    append: true
    group: "{{ apk_signing_group_name | mandatory }}"
    name: "{{ item.key }}"
  loop:
    "{{ apk_signing_users | mandatory | dict2items }}"
  loop_control:
    label: "{{ item.key | to_json }}"
  become:
    true

# https://docs.ansible.com/ansible/latest/modules/copy_module.html
- name:
    "copy : /etc/sudoers.d/{{ item.key }}"
  copy:
    dest: "/etc/sudoers.d/{{ item.key }}"
    mode: "0440"
    content: |
      {{ item.key }} ALL=(ALL) NOPASSWD:/usr/bin/apksigner
    validate:
      "/usr/sbin/visudo --check --file=%s"
  become:
    true
  loop_control:
    label: "{{ item.key | to_json }}"
  loop:
    "{{ apk_signing_users | mandatory | dict2items }}"

# https://docs.ansible.com/ansible/latest/modules/file_module.html
# yamllint disable rule:line-length
- name:
    "set_fact : {{ apk_signing_directory }}/{{ project.key }}.keystore.credentials"
  set_fact:
    apk_signing_hosts_per_project_paths__to_merge:
      "{{ apk_signing_hosts_per_project_paths__to_merge
        | default({})
        | combine({
          apk_signing_directory + '/' + project.key + '.keystore.credentials': {
            'dest': apk_signing_directory + '/' + project.key + '.keystore.credentials',
            'state': 'copy',
            'mode': '0640',
            'owner': 'root',
            'group': apk_signing_group_name,
            'content': content,
            'validate': '/bin/sh -n %s',
            }
          })
        }}"
  vars:
    content: |
      APK_KEYSTORE_NAME={{ project.value.APK_KEYSTORE_NAME | mandatory }}
      APK_KEY_ALIAS_NAME={{ project.value.APK_KEY_ALIAS_NAME | mandatory }}
      APK_STOREPASS={{ project.value.APK_STOREPASS | mandatory }}
      APK_KEYPASS={{ project.value.APK_KEYPASS | mandatory }}
  loop_control:
    loop_var: "project"
  loop:
    "{{ apk_signing_projects | dict2items }}"
# yamllint enable rule:line-length
