# Copyright (c) 2020-present eyeo GmbH
#
# This module is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---

# https://docs.ansible.com/ansible/latest/modules/apt_module.html
- name:
    "apt : jdk_package_name"
  apt:
    cache_valid_time: "{{ apt_cache_valid_time | default(omit) }}"
    default_release: "{{ apt_default_release | default(omit) }}"
    name: "{{ jdk_package_name | default('default-jdk') }}"
    state: "present"
    update_cache: "{{ apt_update_cache | default(omit) }}"
  become:
    true

# https://docs.ansible.com/ansible/latest/modules/group_module.html
- name:
    "group : apk_signing_group_name"
  group:
    name: "{{ apk_signing_group_name | mandatory }}"
  become:
    true

# https://docs.ansible.com/ansible/latest/modules/user_module.html
- name:
    "user : apk_signing_group_name"
  user:
    append: true
    group: "{{ apk_signing_group_name | mandatory }}"
    name: "{{ item.key }}"
  with_dict:
    "{{ apk_signing_users | mandatory }}"
  loop_control:
    label: "{{ item.key | to_json }}"
  become:
    true

# https://docs.ansible.com/ansible/latest/modules/file_module.html
- name:
    "file : apk_signing_group_credentials_source directory"
  file:
    state: "directory"
    path: "{{ credentials_dirname }}"
    owner: "root"
    group: "{{ apk_signing_group_name | mandatory }}"
    mode: "0750"
  vars:
    credentials_dirname:
      "/{{ [apk_signing_group_name,
            (apk_signing_group_credentials_source
              | mandatory
              | dirname
              ).strip('/')]
         | join('/')
         }}"
  register:
    "credentials_directory"
  become:
    true

# https://docs.ansible.com/ansible/latest/modules/copy_module.html
- name:
    "copy : apk_signing_group_credentials_source"
  copy:
    dest:
      "{{ [credentials_directory.path,
           apk_signing_group_credentials_source | mandatory | basename]
        | join('/')
        }}"
    mode: "0640"
    content: |
      APK_KEYSTORE_NAME={{ APK_KEYSTORE_NAME | mandatory }}
      APK_KEY_ALIAS_NAME={{ APK_KEY_ALIAS_NAME | mandatory }}
      APK_STOREPASS={{ APK_STOREPASS | mandatory }}
      APK_KEYPASS={{ APK_KEYPASS | mandatory }}
    validate:
      "/bin/sh -n %s"
    owner: "root"
    group: "{{ apk_signing_group_name }}"
  register:
    "remote_credentials_file"
  become:
    true

# https://docs.ansible.com/ansible/latest/modules/template_module.html
- name:
    "template : /usr/local/bin/apk_signer"
  template:
    src: "./files/apk_signer.j2"
    dest: "/usr/local/bin/apk_signer"
    mode: "0755"
    validate:
      "/bin/sh -n %s"
  become:
    true

# https://docs.ansible.com/ansible/latest/modules/copy_module.html
- name:
    "copy : /etc/sudoers.d/{{ item.key }}"
  copy:
    dest: "/etc/sudoers.d/{{ item.key }}"
    mode: "0440"
    content: |
      {{ item.key }} ALL=(ALL) NOPASSWD:/usr/bin/jarsigner
    validate:
      "/usr/sbin/visudo --check --file=%s"
  become:
    true
  loop_control:
    label: "{{ item.key | to_json }}"
  with_dict:
    "{{ apk_signing_users | mandatory }}"
