# Copyright (c) 2018-2023 eyeo GmbH
#
# This module is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---

# https://docs.ansible.com/ansible/latest/import_tasks_module.html
- import_tasks:
    "tasks/os/main.yml"

# https://docs.ansible.com/ansible/latest/modules/include_tasks_module.html
- include_tasks:
    "{{ custom_common_tasks }}"
  with_first_found:
    - files:
        - "tasks/os/{{ ansible_os_family | lower }}/common.yml"
      skip: true
  loop_control:
    loop_var: "custom_common_tasks"

# https://docs.ansible.com/ansible/latest/modules/fail_module.html
- fail:
    msg: >-
      Ansible hostname {{ ansible_hostname }} does not match inventory hostname
      short {{ inventory_hostname_short }}. Fix /etc/hostname and try again.
  when: "ansible_hostname != inventory_hostname_short"

# https://docs.ansible.com/ansible/latest/modules/fail_module.html
- fail:
    msg: >-
      Ansible FQDN {{ ansible_fqdn }} does not match inventory hostname
      {{ inventory_hostname }}. Fix /etc/hosts and try again.
  when: "ansible_fqdn != inventory_hostname"
