# Copyright (c) 2020-present eyeo GmbH
#
# This module is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---

# https://docs.ansible.com/ansible/latest/modules/blockinfile_module.html
- name:
    "blockinfile : /etc/munin/munin-node.conf"
  blockinfile:
    block: |
      {% for key, value in custom_munin_node_configuration | dictsort %}
      {{ key }} {{ value }}
      {% endfor %}
    insertafter: "EOF"
    path: "/etc/munin/munin-node.conf"
  notify:
    "service : munin-node"
  become:
    true
  when:
    "custom_munin_node_configuration is defined"

# NB: module not available by default
# https://docs.ansible.com/ansible/latest/collections/community/general/dpkg_divert_module.html
# - name:
#     "dpkg-divert : /usr/share/munin/munin-asyncd"
#   dpkg_divert:
#     path: "/usr/share/munin/munin-asyncd"

# TODO: fix actual upstream code to not have a hardcoded 5 minute default
# https://github.com/munin-monitoring/munin/issues/1409
# https://docs.ansible.com/ansible/latest/collections/ansible/posix/patch_module.html
- name:
    "patch : {{ munin_asyncd_plugin_update_rate_patch | default('') }}"
  patch:
    src: "{{ munin_asyncd_plugin_update_rate_patch }}"
    dest: "/usr/share/munin/munin-asyncd"
  notify:
    "service : munin-async"
  become:
    true
  when:
    "munin_asyncd_plugin_update_rate_patch | default('') | length > 0"
