# Copyright (c) 2018-present eyeo GmbH
#
# This module is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---

# action_plugins/merge_variable.py
- name:
    "merge_variable : mysql_users"
  merge_variable:
    suffix: "mysql_users__to_merge"
    name: "mysql_users"
    default: {}

# action_plugins/merge_variable.py
- name:
    "merge_variable : mysql_databases"
  merge_variable:
    suffix: "mysql_databases__to_merge"
    name: "mysql_databases"
    default: {}

# https://docs.ansible.com/ansible/latest/import_role_module.html
# https://gitlab.com/eyeo/devops/ansible-role-mysql
# roles/mysql/server/tasks/main.yml
- import_role:
    name: "mysql/server"
