# Copyright (c) 2026 Josip Rodin
#
# This module is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---

# action_plugins/merge_variable.py
- name:
    "merge_variable : snaps"
  merge_variable:
    default: {}
    name: "snaps"
    suffix: "{{ snaps
              | default('snaps__to_merge') }}"

# https://docs.ansible.com/ansible/latest/modules/package_module.html
- name:
    "package"
  package:
    name:
      - "snapd"
    state: "present"
  become:
    true

# https://docs.ansible.com/projects/ansible/latest/collections/community/general/snap_module.html
- name:
    "snap"
  snap:
    channel: "{{ snap_vars.value.channel | default(omit) }}"
    classic: "{{ snap_vars.value.classic | default(omit) }}"
    dangerous: "{{ snap_vars.value.dangerous | default(omit) }}"
    name: "{{ snap_vars.value.name | default(snap_vars.key) }}"
    options: "{{ snap_vars.value.options | default(omit) }}"
    state: "{{ snap_vars.value.state | default(omit) }}"
  become:
    true
  become_user:
    "{{ snap_vars.value.user | default(omit) }}"
  loop:
    "{{ snaps | dict2items }}"
  loop_control:
    loop_var: "snap_vars"
