id: 2
uid: BK2sZrA4k
orgId: 1
name: Prometheus
type: prometheus
typeName: Prometheus
typeLogoUrl: public/app/plugins/datasource/prometheus/img/prometheus_logo.svg
access: proxy
url: http://localhost:9009/prometheus
user: ""
database: ""
basicAuth: false
isDefault: false
jsonData:
  httpMethod: POST
  prometheusType: Mimir
  prometheusVersion: 2.4.0
readOnly: false
