apiVersion: v1
kind: Secret
metadata:
  name: gitlab-registry-key
  namespace: {{ k8s_gitlab_registry_secret_namespace | default('default') }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ k8s_gitlab_runner_docker_config | b64encode }}
